# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anamreceiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='images_handled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collect',
            name='imported_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='dataset',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
