# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 14:00
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anamreceiver', '0002_auto_20170519_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='targets',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
