# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamreceiver', '0003_collect_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='images_nb_error',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collect',
            name='images_nb_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
