# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anamreceiver', '0005_collect_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='images_handled_on',
            new_name='images_copied_on',
        ),
    ]
