# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-10-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamreceiver', '0006_auto_20170606_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='cercle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collect',
            name='commune',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collect',
            name='nb_submissions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collect',
            name='ona_form_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collect',
            name='ona_scan_form_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
